# Generated by Django 5.2.4 on 2025-08-08 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField(help_text="报告生成日期")),
                ("period_start", models.DateField(help_text="统计周期开始日期")),
                ("period_end", models.DateField(help_text="统计周期结束日期")),
                (
                    "overall_score",
                    models.PositiveIntegerField(default=0, help_text="综合健康评分（0-100）"),
                ),
                (
                    "sleep_score",
                    models.PositiveIntegerField(default=0, help_text="睡眠健康评分（0-100）"),
                ),
                (
                    "exercise_score",
                    models.PositiveIntegerField(default=0, help_text="运动健康评分（0-100）"),
                ),
                (
                    "diet_score",
                    models.PositiveIntegerField(default=0, help_text="饮食健康评分（0-100）"),
                ),
                (
                    "health_grade",
                    models.CharField(
                        choices=[
                            ("excellent", "优秀"),
                            ("good", "良好"),
                            ("fair", "一般"),
                            ("needs_improvement", "需改善"),
                            ("poor", "较差"),
                        ],
                        help_text="健康等级",
                        max_length=20,
                    ),
                ),
                (
                    "health_trend",
                    models.CharField(
                        choices=[
                            ("improving", "改善中"),
                            ("stable", "稳定"),
                            ("declining", "下降"),
                        ],
                        help_text="健康趋势",
                        max_length=20,
                    ),
                ),
                (
                    "key_insights",
                    models.TextField(default="[]", help_text="关键洞察（JSON格式）"),
                ),
                (
                    "recommendations",
                    models.TextField(default="[]", help_text="健康建议（JSON格式）"),
                ),
                (
                    "data_summary",
                    models.TextField(default="{}", help_text="数据摘要（JSON格式）"),
                ),
                (
                    "detailed_analysis",
                    models.TextField(default="{}", help_text="详细分析（JSON格式）"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_reports",
                        to="user.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "健康报告",
                "verbose_name_plural": "健康报告",
                "ordering": ["-report_date", "-created_at"],
                "unique_together": {("user", "period_start", "period_end")},
            },
        ),
    ]
