# Generated by Django 5.2.4 on 2025-08-08 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_healthreport"),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("sleep", "睡眠目标"),
                            ("exercise", "运动目标"),
                            ("diet", "饮食目标"),
                            ("weight", "体重目标"),
                            ("custom", "自定义目标"),
                        ],
                        help_text="目标类型",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(help_text="目标标题", max_length=100)),
                ("description", models.TextField(blank=True, help_text="目标描述")),
                ("target_value", models.FloatField(help_text="目标数值")),
                ("current_value", models.FloatField(default=0, help_text="当前数值")),
                ("unit", models.CharField(help_text="单位（如：小时、次、公斤等）", max_length=20)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "每日"),
                            ("weekly", "每周"),
                            ("monthly", "每月"),
                            ("total", "总计"),
                        ],
                        help_text="完成频率",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(help_text="开始日期")),
                ("end_date", models.DateField(help_text="结束日期")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "进行中"),
                            ("completed", "已完成"),
                            ("paused", "已暂停"),
                            ("cancelled", "已取消"),
                        ],
                        default="active",
                        help_text="目标状态",
                        max_length=20,
                    ),
                ),
                (
                    "progress_percentage",
                    models.FloatField(default=0, help_text="完成百分比"),
                ),
                (
                    "reminder_enabled",
                    models.BooleanField(default=True, help_text="是否启用提醒"),
                ),
                (
                    "reminder_time",
                    models.TimeField(blank=True, help_text="提醒时间", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_goals",
                        to="user.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "健康目标",
                "verbose_name_plural": "健康目标",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GoalProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="记录日期")),
                ("value", models.FloatField(help_text="当日数值")),
                ("notes", models.TextField(blank=True, help_text="备注")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_records",
                        to="user.healthgoal",
                    ),
                ),
            ],
            options={
                "verbose_name": "目标进度记录",
                "verbose_name_plural": "目标进度记录",
                "ordering": ["-date"],
                "unique_together": {("goal", "date")},
            },
        ),
    ]
